### ISSUE TITLE
Say "Thank you"

### ISSUE THREAD

**Issue by captain-miao** [marhan/effective-java-examples#1]
http://java.sun.com/docs/books/effective/index.html is invalid.

Thank you very much.

**Comment by Byron** [comment]
I second this ! 
Fortunately this repository shows up when searching for `effective java book source code`.

**Comment by marhan** [comment]
You are welcome

**Comment by marhan** [comment]
I have adjusted the reame file.

**Comment by OU8N** [comment]
May kind people be blessed with life-long peace.
